# Generated by Django 5.2.7 on 2025-10-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер рейса')),
                ('destination', models.CharField(max_length=100, verbose_name='Пункт назначения')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылета')),
                ('arrival_time', models.DateTimeField(verbose_name='Время прибытия')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('boarding', 'Посадка'), ('departed', 'Вылетел'), ('landed', 'Приземлился'), ('cancelled', 'Отменен')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('capacity', models.IntegerField(default=180, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('passport_number', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Пассажир',
                'verbose_name_plural': 'Пассажиры',
            },
        ),
    ]
