# Generated by Django 5.2.7 on 2025-10-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['departure_time'], 'verbose_name': 'Рейс', 'verbose_name_plural': 'Рейсы'},
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город вылета'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город назначения'),
        ),
    ]
