# Generated by Django 5.2.7 on 2025-10-10 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flight_options_remove_flight_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=20, unique=True, verbose_name='ID агента')),
                ('workstation', models.CharField(max_length=50, verbose_name='Рабочее место')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoardingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_pass_number', models.CharField(max_length=15, unique=True, verbose_name='Номер посадочного талона')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Номер места')),
                ('gate', models.CharField(blank=True, max_length=10, verbose_name='Выход')),
                ('boarding_time', models.DateTimeField(blank=True, null=True, verbose_name='Время посадки')),
                ('check_in_time', models.DateTimeField(auto_now_add=True, verbose_name='Время регистрации')),
                ('status', models.CharField(choices=[('checked_in', 'Зарегистрирован'), ('boarded', 'Прошел посадку'), ('cancelled', 'Отменен')], default='checked_in', max_length=20, verbose_name='Статус')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight', verbose_name='Рейс')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger', verbose_name='Пассажир')),
                ('check_in_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.checkinagent', verbose_name='Агент регистрации')),
            ],
            options={
                'verbose_name': 'Посадочный талон',
                'verbose_name_plural': 'Посадочные талоны',
            },
        ),
    ]
