# Generated by Django 5.2.7 on 2025-10-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_checkinagent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(default='A1', max_length=10, verbose_name='Выход'),
        ),
    ]
