# Generated by Django 5.2.8 on 2025-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_gate'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
